- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - package:
      name: 
      - python3-pip
      - unzip
  - file:
      state: directory
      path: ~/bin
    become: no
  - unarchive:
      dest: ~/bin
      remote_src: yes
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    become: no
