# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
DOCKER_VERSION = "17.05.0"
DOCKER_COMPOSE_VERSION="1.14.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision "shell", inline: <<-SCRIPT
    #wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    #sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    #    /etc/apt/sources.list.d/jenkins.list'
    #sudo apt-get update
    #sudo apt-get install -y openjdk-8-jdk
    #sudo apt-get install -y jenkins
    sudo apt-get update
    sudo apt-get install -y docker.io
    sudo docker run -d --restart always --network host --name jenkins jenkins
  SCRIPT

  config.vm.define "jenkins2" do |jk2|
    jk2.vm.hostname = "jenkins2"
    jk2.vm.network "private_network", ip: "192.168.5.2"
  end

  config.vm.define "jenkins3" do |jk3|
    jk3.vm.hostname = "jenkins3"
    jk3.vm.network "private_network", ip: "192.168.5.3"
  end

  config.vm.define "jenkins4" do |jk4|
    jk4.vm.hostname = "jenkins4"
    jk4.vm.network "private_network", ip: "192.168.5.4"
  end

end
